[dependencies.aloe-audio-processor]
path = "../aloe-audio-processor"
[dependencies.aloe-audio-processor-editor]
path = "../aloe-audio-processor-editor"
[dependencies.aloe-buffers]
path = "../aloe-buffers"
[dependencies.aloe-buttons]
path = "../aloe-buttons"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-events]
path = "../aloe-events"
[dependencies.aloe-graphics]
path = "../aloe-graphics"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-label]
path = "../aloe-label"
[dependencies.aloe-memory]
path = "../aloe-memory"
[dependencies.aloe-midi]
path = "../aloe-midi"
[dependencies.aloe-network]
path = "../aloe-network"
[package]
edition = "2021"
name = "aloe-surround"
version = "0.1.0"