[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-vst-attributes]
path = "../aloe-vst-attributes"
[dependencies.aloe-vst-message]
path = "../aloe-vst-message"
[dependencies.aloe-vst-plugin]
path = "../aloe-vst-plugin"
[dependencies.aloe-vst-types]
path = "../aloe-vst-types"
[package]
edition = "2021"
name = "aloe-vst-host"
version = "0.1.0"