extern crate objc;

#[macro_use] mod imports; use imports::*;

x!{active_textures}
x!{android_gl_callbacks}
x!{app_component_traits}
x!{async_worker}
x!{blending_mode}
x!{cached_image}
x!{cached_image_blocking_worker}
x!{cached_image_cv_displaylink_wrapper}
x!{cached_image_list}
x!{context_attachment}
x!{context_cached_image}
x!{copy_texture_program}
x!{create}
x!{current_shader}
x!{custom_program}
x!{custom_shader}
x!{depth_test_disabler}
x!{dpi}
x!{edge_table_alpha_map}
x!{edge_table_renderer}
x!{flipper}
x!{float_rectangle_renderer}
x!{frame_buffer_image}
x!{frame_buffer_image_data_releaser}
x!{frame_buffer_image_dummy}
x!{frame_buffer_image_reader}
x!{frame_buffer_image_writer}
x!{gl_state}
x!{image_masked_program}
x!{image_params}
x!{image_program}
x!{image_type}
x!{ios_app_inactivity_callback}
x!{ios_background_process_check}
x!{linear_gradient1_masked_program}
x!{linear_gradient1_program}
x!{linear_gradient2_masked_program}
x!{linear_gradient2_program}
x!{linear_gradient_params}
x!{mask_texture_program}
x!{masked_shader_params}
x!{native_context}
x!{native_context_locker}
x!{non_shader_context}
x!{opengl}
x!{opengl_android}
x!{opengl_context}
x!{opengl_framebuffer_impl}
x!{opengl_framebuffer_saved_state}
x!{opengl_helpers}
x!{opengl_ios}
x!{opengl_linux_x11}
x!{opengl_linux_x11_native_context}
x!{opengl_linux_x11_native_context_dummy_component}
x!{opengl_linux_x11_native_context_locker}
x!{opengl_osx_native_context}
x!{opengl_osx_native_context_locker}
x!{opengl_osx_native_context_mouse_forwarding}
x!{opengl_target_saver}
x!{openglappcomponent}
x!{openglframebuffer}
x!{openglhelpers}
x!{openglpixelformat}
x!{openglrenderer}
x!{openglshaderprogram}
x!{opengltexture}
x!{positioned_texture}
x!{radial_gradient_masked_program}
x!{radial_gradient_params}
x!{radial_gradient_program}
x!{rendering_target}
x!{safe_ns_event}
x!{safe_ns_opengl_context}
x!{safe_ns_opengl_view}
x!{saved_state}
x!{shader_base}
x!{shader_context}
x!{shader_declare}
x!{shader_program_attribute}
x!{shader_program_holder}
x!{shader_program_uniform}
x!{shader_programs}
x!{shader_quad_queue}
x!{solid_colour_masked_program}
x!{solid_colour_program}
x!{texture_cache}
x!{texture_info}
x!{texture_magnification_filter}
x!{tiled_image_masked_program}
x!{tiled_image_program}
x!{version}
x!{wgl}
