[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-oboe-flowgraph-filter]
path = "../aloe-oboe-flowgraph-filter"
[package]
edition = "2021"
name = "aloe-oboe-flowgraph-resampler"
version = "0.1.0"