#[macro_use] mod imports; use imports::*;

x!{assign_shared}
x!{baseiids}
x!{cast_help}
x!{classfactoryhelpers}
x!{com_query}
x!{coord}
x!{coreiids}
x!{def_interfaces}
x!{fobject}
x!{fobject_interface}
x!{fobject_iid_initializer}
x!{freleaser}
x!{fuid}
x!{funknown}
x!{funknown_methods}
x!{funknown_private}
x!{funknown_ptr}
x!{futils}
x!{fvariant}
x!{get_uid}
x!{guid_struct}
x!{icloneable}
x!{iid}
x!{ivstprefetchablesupport}
x!{platform_string}
x!{primitive}
x!{query_interface}
x!{refcount}
x!{refcount_methods}
x!{result_codes}
x!{safe_release}
x!{semantic_types}
x!{singleton}
x!{smartpointer}
x!{smtg_use}
x!{string}
x!{swap}
x!{typesizecheck}
x!{uid}
x!{version}
x!{vstinitiids}
x!{vsttypes}
x!{iptr}
x!{optr}
x!{idependent}
x!{iupdatehandler}
