[dependencies]
atomic = "*"
bitfield = "*"
lazy_static = "*"
libc = "*"
modular-bitfield = "*"
num = "*"
parking_lot = "*"
static_assertions = "*"
wchar = "*"
[dependencies.aloe-component]
path = "../aloe-component"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-dsp]
path = "../aloe-dsp"
[dependencies.aloe-dynamics]
path = "../aloe-dynamics"
[dependencies.aloe-filter]
path = "../aloe-filter"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-mixer]
path = "../aloe-mixer"
[dependencies.aloe-oversampling]
path = "../aloe-oversampling"
[dependencies.aloe-processor-chain]
path = "../aloe-processor-chain"
[dependencies.aloe-sample-type]
path = "../aloe-sample-type"
[dependencies.aloe-waveshaper]
path = "../aloe-waveshaper"
[package]
edition = "2021"
name = "aloe-distortion"
version = "0.1.0"