[package]
name = "aloe-rs"
version = "0.1.0"
authors = ["klebs <none>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.aloe_derive]
path = "../aloe_derive"

[dependencies]
#breakpoint = "*"
wchar = "*"
atomic = "*"
static_assertions = "*"
libc = "*"
lazy_static = "*"
num = "*"
bitfield = "*"
modular-bitfield = "*"
parking_lot = "*"
