[dependencies.aloe-audio-device-manager]
path = "../aloe-audio-device-manager"
[dependencies.aloe-audio-devices]
path = "../aloe-audio-devices"
[dependencies.aloe-audio-interface]
path = "../aloe-audio-interface"
[dependencies.aloe-audio-processor]
path = "../aloe-audio-processor"
[dependencies.aloe-buffers]
path = "../aloe-buffers"
[dependencies.aloe-buttons]
path = "../aloe-buttons"
[dependencies.aloe-colour]
path = "../aloe-colour"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-documentwindow]
path = "../aloe-documentwindow"
[dependencies.aloe-events]
path = "../aloe-events"
[dependencies.aloe-filebrowser]
path = "../aloe-filebrowser"
[dependencies.aloe-files]
path = "../aloe-files"
[dependencies.aloe-image]
path = "../aloe-image"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-memory]
path = "../aloe-memory"
[dependencies.aloe-midi]
path = "../aloe-midi"
[dependencies.aloe-player]
path = "../aloe-player"
[dependencies.aloe-properties]
path = "../aloe-properties"
[dependencies.aloe-valuetree]
path = "../aloe-valuetree"
[dependencies.aloe-xml]
path = "../aloe-xml"
[package]
edition = "2021"
name = "aloe-standalone"
version = "0.1.0"