[dependencies.aloe-char]
path = "../aloe-char"
[dependencies.aloe-colour]
path = "../aloe-colour"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-drawables]
path = "../aloe-drawables"
[dependencies.aloe-files]
path = "../aloe-files"
[dependencies.aloe-font]
path = "../aloe-font"
[dependencies.aloe-geometry]
path = "../aloe-geometry"
[dependencies.aloe-graphics]
path = "../aloe-graphics"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-xml]
path = "../aloe-xml"
[package]
edition = "2021"
name = "aloe-svg"
version = "0.1.0"