#[macro_use] mod imports; use imports::*;

x!{arpeggiator}
x!{auv3_synth_editor}
x!{auv3_synth_processor}
x!{command}
x!{command_fifo}
x!{data_model}
x!{data_model_listener}
x!{demo_editor}
x!{demo_processor}
x!{editor}
x!{embedded_ui}
x!{embedded_view_listener}
x!{file_audio_format_reader_factory}
x!{gain_processor}
x!{generic_variant_converter}
x!{ia_affect_processor}
x!{initialize_combobox}
x!{loop_mode}
x!{loop_point_marker}
x!{loop_points_overlay}
x!{main_sampler_view}
x!{make_reader}
x!{material_look_and_feel}
x!{memory_audio_format_reader_factory}
x!{meter_listener}
x!{mp3_sampler_sound}
x!{mp3_sampler_voice}
x!{mpe_legacy_settings_component}
x!{mpe_new_settings_component}
x!{mpe_settings_component}
x!{mpe_settings_data_model}
x!{noise_gate}
x!{playback_position_overlay}
x!{processor_state}
x!{reaper_embedded_view_editor}
x!{reaper_fxembed}
x!{reference_counting_adapter}
x!{ruler}
x!{sample}
x!{sampler_audio_processor}
x!{sampler_audio_processor_editor}
x!{simple_meter}
x!{sine_wave_sound}
x!{sine_wave_voice}
x!{spin_lock_pos_info}
x!{template_command}
x!{visible_range_data_model}
x!{waveform_editor}
x!{waveform_view}
