#[macro_use] mod imports; use imports::*;


x!{android_component_peer_preallocated_image}
x!{android_component_peer_startup_activity_callback_listener}
x!{android_component_peer_view_window_insets_listener}
x!{activity_launcher}
x!{activity_lifecycle_callbacks}
x!{android_accessibility}
x!{android_component_peer}
x!{android_content_sharer_file_observer}
x!{android_content_uri_output_stream}
x!{android_content_uri_resolver}
x!{android_contentsharer}
x!{android_contentsharer_cursor}
x!{android_contentsharer_native_impl}
x!{android_contentsharer_prepare_files_thread}
x!{android_files}
x!{android_font}
x!{android_fonts}
x!{android_ft_typeface_list}
x!{android_graphicscontext}
x!{android_handler}
x!{android_iconhelpers}
x!{android_interface_implementer}
x!{android_jnihelpers}
x!{android_message_queue}
x!{android_network}
x!{android_process}
x!{android_runnable}
x!{android_text_layout}
x!{android_threads}
x!{android_time}
x!{android_typeface}
x!{android_webbrowsercomponent}
x!{android_windowing}
x!{androidviewcomponent}
x!{androidviewcomponent_impl}
x!{connection_thread}
x!{default_font_names}
x!{fragment_overlay}
x!{global_ref}
x!{ip_address}
x!{jni_class_base}
x!{aloe_activity_watcher}
x!{aloe_app_lifecycle}
x!{aloe_http_stream}
x!{aloe_start}
x!{aloe_web_chrome_client}
x!{aloe_web_view_21_bytecode}
x!{aloe_web_view_client16}
x!{local_ref}
x!{mac_address}
x!{media_scanner_connection_client}
x!{message_manager}
x!{multicast_lock}
x!{native_android_bluetooth_midi_device}
x!{native_android_bluetooth_midi_device_pairing_dialogue}
x!{native_android_bluetooth_midi_devices_list_box}
x!{native_android_bluetooth_midi_devices_list_box_pair_device_thread}
x!{native_android_bluetooth_midi_interface}
x!{native_android_bluetooth_midi_selector_overlay}
x!{native_android_midi_device_manager}
x!{native_android_midi_java_bytecode}
x!{native_android_midi_jni_declarations}
x!{process}
x!{single_media_scanner}
x!{stream_closer}
x!{surface_holder_callback}
x!{system_java_class_comparator}
x!{system_stats}
x!{thread}
x!{typeface}
x!{url}
x!{web_browser_component}
x!{web_browser_component_impl}
x!{web_input_stream}
