#[macro_use] mod imports; use imports::*;

x!{android_notification}
x!{android_pushnotifications}
x!{android_pushnotifications_impl}
x!{demo_aux_actions_view}
x!{demo_param_controls}
x!{demo_params_view}
x!{demo_remote_view}
x!{demo_row_component}
x!{demo_tabbed_component}
x!{examples_utilities_pushnotificationsdemo}
x!{firebase_instance_id}
x!{firebase_instance_id_service}
x!{firebase_messaging}
x!{firebase_messaging_service}
x!{notification_action_builder}
x!{notification_builder_api16}
x!{notification_builder_api17}
x!{notification_builder_api20}
x!{notification_builder_api21}
x!{notification_builder_api24}
x!{notification_builder_api26}
x!{notification_builder_base}
x!{notification_channel}
x!{notification_channel_group}
x!{notification_manager_api23}
x!{notification_manager_api24}
x!{notification_manager_api26}
x!{notification_manager_base}
x!{push_notification_action_progress}
x!{push_notification_badge_icon_type}
x!{push_notification_group_alert_behavior}
x!{push_notification_led_blink_pattern}
x!{push_notification_listener}
x!{push_notification_lock_screen_appearance}
x!{push_notification_priority}
x!{push_notification_timestamp_visibility}
x!{push_notification_type}
x!{remote_input}
x!{remote_input_builder}
x!{remote_message}
x!{remote_message_builder}
x!{remote_message_notification}
x!{status_bar_notification}
