[dependencies.aloe-buttons]
path = "../aloe-buttons"
[dependencies.aloe-colour]
path = "../aloe-colour"
[dependencies.aloe-component]
path = "../aloe-component"
[dependencies.aloe-critical-section]
path = "../aloe-critical-section"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-documentwindow]
path = "../aloe-documentwindow"
[dependencies.aloe-editor]
path = "../aloe-editor"
[dependencies.aloe-events]
path = "../aloe-events"
[dependencies.aloe-files]
path = "../aloe-files"
[dependencies.aloe-graphics]
path = "../aloe-graphics"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-label]
path = "../aloe-label"
[dependencies.aloe-lookandfeel]
path = "../aloe-lookandfeel"
[dependencies.aloe-memory]
path = "../aloe-memory"
[dependencies.aloe-network]
path = "../aloe-network"
[dependencies.aloe-slider]
path = "../aloe-slider"
[dependencies.aloe-texteditor]
path = "../aloe-texteditor"
[dependencies.aloe-viewport]
path = "../aloe-viewport"
[package]
edition = "2021"
name = "aloe-live-constant-editor"
version = "0.1.0"