#![feature(associated_type_defaults)]

#[macro_use] mod imports; use imports::*;

x!{accessibility_action_component}
x!{accessibility_demo}
x!{accessible_component}
x!{actions_component}
x!{alert_box_result_chosen}
x!{animated_app_Demo}
x!{animation_demo}
x!{announcements_component}
x!{async_alertbox_result_chosen}
x!{ball_component}
x!{ball_generator_component}
x!{basic_window}
x!{bouncing_ball_component}
x!{bouncing_ball_wavetable_demo}
x!{bouncing_balls_container}
x!{bubble_message}
x!{burger_menu_header}
x!{buttons_component}
x!{buttons_page}
x!{camera_demo}
x!{code_editor_demo}
x!{colour_change_button}
x!{colour_selector_window}
x!{component_demo}
x!{component_factory}
x!{component_transforms_demo}
x!{content_component}
x!{controllers_component}
x!{corner_dragger}
x!{custom_look_and_feel}
x!{custom_navigation_component}
x!{custom_tab_button}
x!{custom_toolbar_combobox}
x!{custom_widget_component}
x!{demo_background_thread}
x!{demo_browser_component}
x!{demo_button_property_component}
x!{demo_controls_overlay}
x!{demo_data_sorter}
x!{demo_flex_panel}
x!{demo_holder_component}
x!{demo_multi_document_panel}
x!{demo_slider_property_component}
x!{demo_tabbed_component}
x!{demo_toolbar_item_factory}
x!{dialog_type}
x!{dialogs_demo}
x!{drag_and_drop_demo}
x!{drag_and_drop_demo_target}
x!{editable_text_custom_component}
x!{flex_box_demo}
x!{glyphs_demo}
x!{graphics_demo}
x!{graphics_demo_base}
x!{grid_demo}
x!{grid_item_panel}
x!{hello_world_demo}
x!{images_demo}
x!{images_rendering_demo}
x!{info_component}
x!{info_icon}
x!{aloe_widgets}
x!{key_mappings_demo}
x!{key_press_target}
x!{lines_demo}
x!{look_and_feel_demo}
x!{look_and_feel_demo_component}
x!{mdi_demo}
x!{menu_page}
x!{menus_demo}
x!{menus_demo_inner_command_target}
x!{menus_demo_outer_Command_target}
x!{misc_page}
x!{movie_component_with_file_browser}
x!{multi_touch_demo}
x!{multi_touch_demo_trail}
x!{name_and_role}
x!{navigable_component}
x!{navigable_components_holder}
x!{note}
x!{opengl_app_demo}
x!{opengl_app_demo_attributes}
x!{opengl_app_demo_builtin_texture}
x!{opengl_app_demo_shader_preset}
x!{opengl_app_demo_shape}
x!{opengl_app_demo_shape_vertex_buffer}
x!{opengl_app_demo_texture_from_asset}
x!{opengl_app_demo_texture_from_file}
x!{opengl_app_demo_uniforms}
x!{opengl_app_demo_vertex}
x!{opengl_demo}
x!{opengl_demo2d}
x!{opengl_demo2d_shader_preset}
x!{opengl_get_presets}
x!{paths_demo}
x!{popup_menu_look_and_feel}
x!{properties_demo}
x!{radio_buttons_group_component}
x!{ranged_value_component}
x!{rating_column_custom_component}
x!{rectangle_fill_types_demo}
x!{sliders_component}
x!{sliders_page}
x!{snapping_slider}
x!{source_item_listbox_components}
x!{square_look_and_feel}
x!{state_component}
x!{state_component_property}
x!{strokes_demo}
x!{svg_demo}
x!{table_demo_component}
x!{test_list_component}
x!{toggle_light_component}
x!{toggle_light_grid_component}
x!{toolbar_demo_comp}
x!{tree_view_component}
x!{tree_view_component_root_item}
x!{value_interface_component}
x!{video_demo}
x!{web_browser_demo}
x!{widgets_demo}
x!{windows_demo}
