[dependencies]
objc = "*"
objc-foundation = "0.1"
objc_id = "*"
coreaudio-rs = "*"
[dependencies.icrate]
features = [ "Foundation", "Foundation_NSError", "Foundation_NSNotification" ]
version = "*"
[dependencies.aloe-au]
path = "../aloe-au"
[dependencies.aloe-au-base]
path = "../aloe-au-base"
[dependencies.aloe-audio-device-manager]
path = "../aloe-audio-device-manager"
[dependencies.aloe-audio-interface]
path = "../aloe-audio-interface"
[dependencies.aloe-bigint]
path = "../aloe-bigint"
[dependencies.aloe-buffers]
path = "../aloe-buffers"
[dependencies.aloe-critical-section]
path = "../aloe-critical-section"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-memory]
path = "../aloe-memory"
[dependencies.aloe-midi]
path = "../aloe-midi"
[dependencies.aloe-network]
path = "../aloe-network"
[dependencies.aloe-playhead]
path = "../aloe-playhead"
[dependencies.aloe-windowing]
path = "../aloe-windowing"
[package]
edition = "2021"
name = "aloe-ios-audio"
version = "0.1.0"
