crate::ix!();

/**
  | Represents a purchase of a product in
  | the store.
  |
  */
pub struct InAppPurchase
{
    /**
      | A unique order identifier for the transaction
      | (generated by the store).
      |
      */
    order_id:                String,


    /**
      | A unique identifier of in-app product
      | that was purchased.
      |
      */
    product_id:              String,


    /**
      | This will be bundle ID on iOS and package
      | name on Android, of the application
      | for which this in-app product was purchased.
      |
      */
    application_bundle_name: String,


    /**
      | Date of the purchase (in ISO8601 format).
      |
      */
    purchase_time:           String,


    /**
      | Android only: purchase token that should
      | be used to consume purchase, provided
      | that In-App product is consumable.
      |
      */
    purchase_token:          String,
}

