#[macro_use] mod imports; use imports::*;

x!{ambisonics}
x!{bus_map_composite}
x!{cached_param_values}
x!{component_restarter}
x!{declare}
x!{description_factory}
x!{description_listener}
x!{dll_handle}
x!{dll_handle_cache}
x!{edit_controller_parameter_dispatcher}
x!{float_cache}
x!{get_arrangement_for_bus}
x!{get_channel_set_for_speaker_arrangement}
x!{get_channel_type}
x!{get_speaker_type}
x!{get_vst3_speaker_arrangement}
x!{getters}
x!{interface_result_with_deferred_add_ref}
x!{midi_event_list}
x!{param_id}
x!{param_value_queue}
x!{parameter_changes}
x!{query_interface_result}
x!{run_loop}
x!{run_loop_timer_caller}
x!{smart_ptr}
x!{stored_midi_mapping}
x!{test_for}
x!{to_process_context}
x!{vst3_buffer_exchange}
x!{vst3_component_holder}
x!{vst3_host_context}
x!{vst3_host_context_attribute_list}
x!{vst3_host_context_context_menu}
x!{vst3_host_context_message}
x!{vst3_host_context_message_map}
x!{vst3_module_handle}
x!{vst3_parameter}
x!{vst3_plugin_format}
x!{vst3_plugin_instance}
x!{vst3_plugin_window}
x!{vst3_plugin_window_child_component}
x!{vst3_warn}
x!{vst3clientextensions}
