#[macro_use] mod imports; use imports::*;

x!{alignment}
x!{audio_data}
x!{audio_data_big_endian}
x!{audio_data_const}
x!{audio_data_converters}
x!{audio_data_float32}
x!{audio_data_int16}
x!{audio_data_int24}
x!{audio_data_int24_in_32}
x!{audio_data_int32}
x!{audio_data_int8}
x!{audio_data_interleaved}
x!{audio_data_little_endian}
x!{audio_data_native_endian}
x!{audio_data_non_const}
x!{audio_data_non_interleaved}
x!{audio_data_pointer}
x!{audio_data_uint8}
x!{audio_process_load_measurer_scoped_timer}
x!{basic_ops32}
x!{basic_ops32_neon}
x!{basic_ops64}
x!{basic_ops64_neon}
x!{channel_set}
x!{channel_type}
x!{converter}
x!{converter_instance}
x!{detail}
x!{float_vector_operations}
x!{increment}
x!{minmax_mode}
x!{mode_type}
x!{process_load_measurer}
x!{sample_buffer}
x!{scoped_no_denormals}
x!{sign_mask}
x!{snap_to_zero}
x!{vec_ops}
x!{vec_ops_neon}
