[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-oboe-core]
path = "../aloe-oboe-core"
[dependencies.aloe-oboe-fixedblockrw]
path = "../aloe-oboe-fixedblockrw"
[dependencies.aloe-oboe-flowgraph-filter]
path = "../aloe-oboe-flowgraph-filter"
[dependencies.aloe-oboe-flowgraph-node]
path = "../aloe-oboe-flowgraph-node"
[dependencies.aloe-oboe-flowgraph-resampler]
path = "../aloe-oboe-flowgraph-resampler"
[dependencies.aloe-oboe-flowgraph-sink]
path = "../aloe-oboe-flowgraph-sink"
[dependencies.aloe-oboe-flowgraph-source]
path = "../aloe-oboe-flowgraph-source"
[dependencies.aloe-oboe-sourcefloatcaller]
path = "../aloe-oboe-sourcefloatcaller"
[dependencies.aloe-oboe-stream]
path = "../aloe-oboe-stream"
[package]
edition = "2021"
name = "aloe-oboe-flowgraph-converter"
version = "0.1.0"