#[macro_use] mod imports; use imports::*;

x!{addpair1}
x!{addpair}
x!{applyforce1}
x!{applyforce}
x!{bodytypes1}
x!{bodytypes}
x!{breakable1}
x!{breakable}
x!{bridge1}
x!{bridge}
x!{bullettest1}
x!{bullettest}
x!{cantilever1}
x!{cantilever}
x!{car1}
x!{car}
x!{chain1}
x!{chain}
x!{charactercollision1}
x!{charactercollision}
x!{collision_b2broadphase}
x!{collision_b2collidecircle}
x!{collision_b2collideedge}
x!{collision_b2collidepolygon}
x!{collision_b2collision}
x!{collision_b2distance}
x!{collision_b2dynamictree}
x!{collision_b2timeofimpact}
x!{collision_shapes_b2chainshape}
x!{collision_shapes_b2circleshape}
x!{collision_shapes_b2edgeshape}
x!{collision_shapes_b2polygonshape}
x!{collision_shapes_b2shape}
x!{collisionfiltering1}
x!{collisionfiltering}
x!{collisionprocessing1}
x!{collisionprocessing}
x!{common_b2blockallocator}
x!{common_b2draw}
x!{common_b2growablestack}
x!{common_b2math}
x!{common_b2settings}
x!{common_b2stackallocator}
x!{common_b2timer}
x!{compoundshapes1}
x!{compoundshapes}
x!{confined1}
x!{confined}
x!{continuoustest1}
x!{continuoustest}
x!{distancetest1}
x!{distancetest}
x!{dominos1}
x!{dominos}
x!{dumpshell1}
x!{dumpshell}
x!{dynamics_b2body}
x!{dynamics_b2contactmanager}
x!{dynamics_b2fixture}
x!{dynamics_b2island}
x!{dynamics_b2timestep}
x!{dynamics_b2worldcallbacks}
x!{dynamics_b2world}
x!{dynamics_contacts_b2chainandcirclecontact}
x!{dynamics_contacts_b2chainandpolygoncontact}
x!{dynamics_contacts_b2circlecontact}
x!{dynamics_contacts_b2contactsolver}
x!{dynamics_contacts_b2contact}
x!{dynamics_contacts_b2edgeandcirclecontact}
x!{dynamics_contacts_b2edgeandpolygoncontact}
x!{dynamics_contacts_b2polygonandcirclecontact}
x!{dynamics_contacts_b2polygoncontact}
x!{dynamics_joints_b2distancejoint}
x!{dynamics_joints_b2frictionjoint}
x!{dynamics_joints_b2gearjoint}
x!{dynamics_joints_b2joint}
x!{dynamics_joints_b2mousejoint}
x!{dynamics_joints_b2prismaticjoint}
x!{dynamics_joints_b2pulleyjoint}
x!{dynamics_joints_b2revolutejoint}
x!{dynamics_joints_b2ropejoint}
x!{dynamics_joints_b2weldjoint}
x!{dynamics_joints_b2wheeljoint}
x!{dynamictreetest1}
x!{dynamictreetest}
x!{edgeshapes1}
x!{edgeshapes}
x!{edgetest1}
x!{edgetest}
x!{example_box2d_demo}
x!{gears1}
x!{gears}
x!{onesidedplatform1}
x!{onesidedplatform}
x!{pinball1}
x!{pinball}
x!{polycollision1}
x!{polycollision}
x!{polyshapes1}
x!{polyshapes}
x!{prismatic1}
x!{prismatic}
x!{pulleys1}
x!{pulleys}
x!{pyramid1}
x!{pyramid}
x!{raycast1}
x!{raycast}
x!{revolute1}
x!{revolute}
x!{rope1}
x!{rope_b2rope}
x!{ropejoint1}
x!{ropejoint}
x!{rope}
x!{sensortest1}
x!{sensortest}
x!{shapeediting1}
x!{shapeediting}
x!{slidercrank1}
x!{slidercrank}
x!{spherestack1}
x!{spherestack}
x!{testentries1}
x!{testentries}
x!{theojansen1}
x!{theojansen}
x!{tiles1}
x!{tiles}
x!{timeofimpact1}
x!{timeofimpact}
x!{tumbler1}
x!{tumbler}
x!{utils_box2drenderer}
x!{varyingfriction1}
x!{varyingfriction}
x!{varyingrestitution1}
x!{varyingrestitution}
x!{verticalstack1}
x!{verticalstack}
x!{web1}
x!{web}
