[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-vst-note-expression]
path = "../aloe-vst-note-expression"
[dependencies.aloe-vst-thread]
path = "../aloe-vst-thread"
[dependencies.aloe-vst-types]
path = "../aloe-vst-types"
[package]
edition = "2021"
name = "aloe-vst-events"
version = "0.1.0"
