[dependencies.aloe-buttons]
path = "../aloe-buttons"
[dependencies.aloe-component]
path = "../aloe-component"
[dependencies.aloe-container]
path = "../aloe-container"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-events]
path = "../aloe-events"
[dependencies.aloe-geometry]
path = "../aloe-geometry"
[dependencies.aloe-graphics]
path = "../aloe-graphics"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-label]
path = "../aloe-label"
[dependencies.aloe-memory]
path = "../aloe-memory"
[dependencies.aloe-mouse]
path = "../aloe-mouse"
[package]
edition = "2021"
name = "aloe-sidepanel"
version = "0.1.0"