[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-events]
path = "../aloe-events"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-keyboard]
path = "../aloe-keyboard"
[dependencies.aloe-parameter-type]
path = "../aloe-parameter-type"
[package]
edition = "2021"
name = "aloe-selection"
version = "0.1.0"