[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-url]
path = "../aloe-url"
[dependencies.aloe-variant]
path = "../aloe-variant"
[package]
edition = "2021"
name = "aloe-notifications"
version = "0.1.0"