[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-oboe-core]
path = "../aloe-oboe-core"
[dependencies.aloe-oboe-fixedblockrw]
path = "../aloe-oboe-fixedblockrw"
[dependencies.aloe-oboe-flowgraph-source]
path = "../aloe-oboe-flowgraph-source"
[dependencies.aloe-oboe-stream]
path = "../aloe-oboe-stream"
[package]
edition = "2021"
name = "aloe-oboe-sourcefloatcaller"
version = "0.1.0"