[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-vst-midi]
path = "../aloe-vst-midi"
[dependencies.aloe-vst-plugview]
path = "../aloe-vst-plugview"
[dependencies.aloe-vst-types]
path = "../aloe-vst-types"
[package]
edition = "2021"
name = "aloe-vst-inter-app"
version = "0.1.0"