[dependencies]
num = "*"
[dependencies.aloe-buffers]
path = "../aloe-buffers"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-deps]
path = "../aloe-deps"
[package]
edition = "2021"
name = "aloe-smoothed-value"
version = "0.1.0"
