[dependencies]
x11 = "*"
[dependencies.aloe-component]
path = "../aloe-component"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-desktop]
path = "../aloe-desktop"
[dependencies.aloe-events]
path = "../aloe-events"
[dependencies.aloe-geometry]
path = "../aloe-geometry"
[dependencies.aloe-graphics]
path = "../aloe-graphics"
[dependencies.aloe-image]
path = "../aloe-image"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-keyboard]
path = "../aloe-keyboard"
[dependencies.aloe-memory]
path = "../aloe-memory"
[dependencies.aloe-mouse]
path = "../aloe-mouse"
[dependencies.aloe-string]
path = "../aloe-string"
[dependencies.aloe-threads]
path = "../aloe-threads"
[dependencies.aloe-time]
path = "../aloe-time"
[dependencies.aloe-windowing]
path = "../aloe-windowing"
[dependencies.aloe-xembed]
path = "../aloe-xembed"
[package]
edition = "2021"
name = "aloe-x11"
version = "0.1.0"