[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-simd-deps]
path = "../aloe-simd-deps"
[package]
edition = "2021"
name = "aloe-simd-fallback"
version = "0.1.0"