[dependencies]
#webkit2gtk = "*"
libc = "*"
[dependencies.aloe-component]
path = "../aloe-component"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-events]
path = "../aloe-events"
[dependencies.aloe-files]
path = "../aloe-files"
[dependencies.aloe-graphics]
path = "../aloe-graphics"
[dependencies.aloe-identifier]
path = "../aloe-identifier"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-memory]
path = "../aloe-memory"
[dependencies.aloe-network]
path = "../aloe-network"
[dependencies.aloe-string]
path = "../aloe-string"
[dependencies.aloe-threads]
path = "../aloe-threads"
[dependencies.aloe-variant]
path = "../aloe-variant"
[dependencies.aloe-x11]
path = "../aloe-x11"
[dependencies.aloe-xembed]
path = "../aloe-xembed"
[package]
edition = "2021"
name = "aloe-webbrowser"
version = "0.1.0"
