[dependencies]
atomic = "*"
bitfield = "*"
lazy_static = "*"
libc = "*"
modular-bitfield = "*"
num = "*"
parking_lot = "*"
static_assertions = "*"
wchar = "*"
[dependencies.aloe-char]
path = "../aloe-char"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-dynamic-object]
path = "../aloe-dynamic-object"
[dependencies.aloe-files]
path = "../aloe-files"
[dependencies.aloe-identifier]
path = "../aloe-identifier"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-memory]
path = "../aloe-memory"
[dependencies.aloe-time]
path = "../aloe-time"
[dependencies.aloe-variant]
path = "../aloe-variant"
[package]
edition = "2021"
name = "aloe-script"
version = "0.1.0"