[dependencies]
libc = "*"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-vst-buffer]
path = "../aloe-vst-buffer"
[dependencies.aloe-vst-component]
path = "../aloe-vst-component"
[dependencies.aloe-vst-edit]
path = "../aloe-vst-edit"
[dependencies.aloe-vst-stream]
path = "../aloe-vst-stream"
[dependencies.aloe-vst-types]
path = "../aloe-vst-types"
[dependencies.aloe-vst-units]
path = "../aloe-vst-units"
[package]
edition = "2021"
name = "aloe-vst-presetfile"
version = "0.1.0"
