#[macro_use] mod imports; use imports::*;

x!{analysis}
x!{backends}
x!{bitrate}
x!{bitwise}
x!{block}
x!{books_coupled_res_books_51}
x!{books_coupled_res_books_stereo}
x!{books_floor_floor_books}
x!{books_uncoupled_res_books_uncoupled}
x!{codebook}
x!{codec_internal}
x!{codec}
x!{crctable}
x!{envelope}
x!{floor0}
x!{floor1}
x!{framing}
x!{highlevel}
x!{info}
x!{libvorbis_window}
x!{lookup_data}
x!{lookup}
x!{lpc}
x!{lsp}
x!{mapping0}
x!{masking}
x!{mdct}
x!{misc}
x!{modes_floor_all}
x!{modes_psych_11}
x!{modes_psych_16}
x!{modes_psych_44}
x!{modes_psych_8}
x!{modes_residue_16}
x!{modes_residue_44p51}
x!{modes_residue_44u}
x!{modes_residue_44}
x!{modes_residue_8}
x!{modes_setup_11}
x!{modes_setup_16}
x!{modes_setup_22}
x!{modes_setup_32}
x!{modes_setup_44p51}
x!{modes_setup_44u}
x!{modes_setup_44}
x!{modes_setup_8}
x!{modes_setup_x}
x!{oggvorbisaudioformat}
x!{ogg}
x!{os_types}
x!{os}
x!{psy}
x!{registry}
x!{res0}
x!{scales}
x!{sharedbook}
x!{smallft}
x!{synthesis}
x!{vorbisenc1}
x!{vorbisenc}
x!{vorbisfile1}
x!{vorbisfile}
