[dependencies.aloe-audio-interface]
path = "../aloe-audio-interface"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-sample-type]
path = "../aloe-sample-type"
[package]
edition = "2021"
name = "aloe-processor-chain"
version = "0.1.0"