[dependencies]
freetype-sys = "*"
core-foundation-sys = "*"
[dependencies.aloe-audio-interface]
path = "../aloe-audio-interface"
[dependencies.aloe-audio-plugin-format]
path = "../aloe-audio-plugin-format"
[dependencies.aloe-audio-plugin-instance]
path = "../aloe-audio-plugin-instance"
[dependencies.aloe-audio-processor-editor]
path = "../aloe-audio-processor-editor"
[dependencies.aloe-buffers]
path = "../aloe-buffers"
[dependencies.aloe-component]
path = "../aloe-component"
[dependencies.aloe-core]
path = "../aloe-core"
[dependencies.aloe-critical-section]
path = "../aloe-critical-section"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-events]
path = "../aloe-events"
[dependencies.aloe-files]
path = "../aloe-files"
[dependencies.aloe-geometry]
path = "../aloe-geometry"
[dependencies.aloe-graphics]
path = "../aloe-graphics"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-keyboard]
path = "../aloe-keyboard"
[dependencies.aloe-memory]
path = "../aloe-memory"
[dependencies.aloe-midi]
path = "../aloe-midi"
[dependencies.aloe-network]
path = "../aloe-network"
[dependencies.aloe-nsview]
path = "../aloe-nsview"
[dependencies.aloe-param]
path = "../aloe-param"
[dependencies.aloe-string]
path = "../aloe-string"
[dependencies.aloe-vst-midi]
path = "../aloe-vst-midi"
[dependencies.aloe-vst-parameters]
path = "../aloe-vst-parameters"
[dependencies.aloe-vst-types]
path = "../aloe-vst-types"
[dependencies.aloe-xml]
path = "../aloe-xml"
[package]
edition = "2021"
name = "aloe-vst-pluginformat"
version = "0.1.0"
