[dependencies.aloe-bigint]
path = "../aloe-bigint"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-deps]
path = "../aloe-deps"
[package]
edition = "2021"
name = "aloe-random"
version = "0.1.0"