[dependencies]
modular-bitfield = "*"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-geometry]
path = "../aloe-geometry"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-memory]
path = "../aloe-memory"
[package]
edition = "2021"
name = "aloe-colour"
version = "0.1.0"
