#[macro_use] mod imports; use imports::*;

x!{active_channels}
x!{active_sense}
x!{query_nodes}
x!{add_bus}
x!{add_channel}
x!{add_event}
x!{add_node}
x!{add_parameter}
x!{aftertouch}
x!{all_controllers_off}
x!{all_sound_off}
x!{ambisonics}
x!{audio_format_manager}
x!{audio_format_reader}
x!{audio_format_writer}
x!{audio_format}
x!{audio_io_device_callback}
x!{audio_io_device_interface}
x!{audio_io_device}
x!{audio_plugin_format_traits}
x!{audio_processor_bus_interface}
x!{audio_processor_buses_layout_interface}
x!{audio_processor_changed}
x!{audio_processor_curve}
x!{audio_processor_editor_host_context}
x!{audio_processor_inout}
x!{audio_processor_interface_traits}
x!{audio_processor_listener_change_details}
x!{audio_processor_listener}
x!{audio_processor_parameter_listener}
x!{audio_processor_track_properties}
x!{audio_processor_wrapper_type}
x!{audio_source_channel_info}
x!{audio_source}
x!{bit_depth}
x!{block_size}
x!{buffer_overrun}
x!{buffer_size}
x!{bus_config}
x!{bus_direction}
x!{bus_layout}
x!{bus_properties}
x!{bus}
x!{bypass}
x!{callback_lock}
x!{change_gesture}
x!{channel_count}
x!{channel_layout}
x!{channel_pressure}
x!{channel_set_layout}
x!{channel_set}
x!{channel_type}
x!{channel}
x!{check_can_add_bus}
x!{check_connection}
x!{check_midi_behavior}
x!{check_status}
x!{clear}
x!{compression}
x!{connect}
x!{constrain}
x!{contains_layout}
x!{control_highlight}
x!{control_panel}
x!{corner_component}
x!{deprecation}
x!{description}
x!{disconnect}
x!{discrete_channels}
x!{editor_interface}
x!{editor}
x!{enable}
x!{end_of_track}
x!{error_handling}
x!{extensions_visitor}
x!{extensions}
x!{file_handler}
x!{file_pos}
x!{find_audio_format}
x!{five_point_surround}
x!{flush}
x!{full_frame}
x!{get_event}
x!{get_next}
x!{get_processor}
x!{gm_instrument}
x!{graph_connection}
x!{graph_node_and_channel}
x!{graph_node_id}
x!{graph_node}
x!{graph}
x!{handle_async}
x!{highlight_info}
x!{host_context}
x!{host_display}
x!{initialize}
x!{key_signature}
x!{latency}
x!{layout}
x!{lcr_surround}
x!{listener}
x!{master_volume}
x!{max_levels}
x!{memory_mapped_audio_format_reader}
x!{memory_map}
x!{memory}
x!{message_length}
x!{meta_event}
x!{midi_behavior}
x!{midi_buffer}
x!{midi_channel_event}
x!{midi_clock}
x!{midi_controller_presence}
x!{midi_controller}
x!{midi_machine_control}
x!{midi_message_factory}
x!{midi_message_variable_length}
x!{midi_message}
x!{midi_note}
x!{midi_state_machine}
x!{names}
x!{note_number}
x!{note_on}
x!{note_velocity}
x!{open_close}
x!{param_change}
x!{param_listener}
x!{parameter_category}
x!{parameter_group}
x!{parameter_steps}
x!{parameter_tree}
x!{param}
x!{pitch_wheel}
x!{pitchbend}
x!{platform_specific}
x!{play_config}
x!{playhead}
x!{plugin_description}
x!{plugin_instance}
x!{plugin_type}
x!{precision}
x!{prepare}
x!{process_block}
x!{program_change}
x!{program}
x!{quality}
x!{quarter_frame}
x!{query_bus}
x!{query_channel_types}
x!{query_parameter}
x!{rate}
x!{raw_data}
x!{read_samples}
x!{read_variable_length}
x!{realtime}
x!{refresh}
x!{register_audio_format}
x!{rendering_sequence}
x!{reset}
x!{resize}
x!{response_curve}
x!{rhythm_instrument}
x!{sample_position}
x!{sample_rate}
x!{scale_factor}
x!{scan}
x!{search}
x!{set_num_channels}
x!{set_processing_enabled}
x!{set_value_notify}
x!{seven_point_surround}
x!{six_point_surround}
x!{smpte_timecode}
x!{soft_pedal}
x!{song_position}
x!{sostenuto_pedal}
x!{speaker_arrangement}
x!{start_stop}
x!{state}
x!{stereo_surround}
x!{surround_mode}
x!{suspend}
x!{sustain_pedal}
x!{system_exclusion_message}
x!{tail_length}
x!{tempo}
x!{text_event}
x!{time_signature}
x!{timestamp}
x!{topology}
x!{touch}
x!{track_event}
x!{track_name_event}
x!{track_properties}
x!{update_peer}
x!{wave_channel_mask}
x!{write_from}
x!{xml}
