crate::ix!();

pub trait MidiMessageInterface 
: GetRawData
+ GetRawDataSize
+ GetTimeStamp
+ SetTimeStamp
+ AddToTimeStamp
+ IsHeapAllocated
+ GetData
+ FloatValueToMidiByte
+ PitchBendToPitchWheelPos
+ ReadVariableLengthValue
+ ReadVariableLengthVal
+ GetMessageLengthFromFirstByte
+ NewFromBlockOfData
+ New1ByteShortMessage
+ New2ByteShortMessage
+ New3ByteShortMessage
+ NewFromOtherMidiMessageWithDifferentTimestamp
+ NewFromMidiStream

/*
   | Returns a human-readable description
   | of the midi message as a string, for example
   | "Note On C#3 Velocity 120 Channel 1".
   |
   */
+ GetDescription
+ CreateWithTimeStamp
+ GetChannel
+ IsForChannel
+ SetChannel
+ IsNoteOn
+ IsNoteOff
+ IsNoteOnOrOff
+ GetNoteNumber
+ SetNoteNumber
+ GetVelocity
+ GetFloatVelocity
+ SetVelocity
+ MultiplyVelocity
+ IsAftertouch
+ GetAftertouchValue
+ AftertouchChange
+ IsChannelPressure
+ GetChannelPressureValue
+ ChannelPressureChange
+ IsSustainPedalOn
+ IsSustainPedalOff
+ IsSostenutoPedalOn
+ IsSostenutoPedalOff
+ IsSoftPedalOn
+ IsSoftPedalOff
+ IsProgramChange
+ GetProgramChangeNumber
+ ProgramChange
+ IsPitchWheel
+ GetPitchWheelValue
+ PitchWheel
+ IsController
+ IsControllerOfType
+ GetControllerNumber
+ GetControllerValue
+ ControllerEvent
+ NoteOn
+ NoteOnWithFloatingPointVelocity
+ NoteOffWithU8Velocity
+ NoteOffWithF32Velocity
+ NoteOff
+ AllNotesOff
+ AllSoundOff
+ IsAllSoundOff
+ IsResetAllControllers
+ AllControllersOff
+ MasterVolume
+ IsSysEx
+ CreateSysExMessage
+ GetSysExData
+ GetSysExDataSize
+ IsMetaEvent
+ IsActiveSense
+ GetMetaEventType
+ GetMetaEventLength
+ GetMetaEventData
+ IsTrackMetaEvent
+ IsEndOfTrackMetaEvent
+ IsTextMetaEvent
+ GetTextFromTextMetaEvent
+ TextMetaEvent
+ IsTrackNameEvent
+ IsTempoMetaEvent
+ IsMidiChannelMetaEvent
+ GetMidiChannelMetaEventChannel
+ GetTempoSecondsPerQuarterNote
+ GetTempoMetaEventTickLength
+ TempoMetaEvent
+ IsTimeSignatureMetaEvent
+ GetTimeSignatureInfo
+ TimeSignatureMetaEvent
+ MidiChannelMetaEvent
+ IsKeySignatureMetaEvent
+ GetKeySignatureNumberOfSharpsOrFlats
+ IsKeySignatureMajorKey
+ KeySignatureMetaEvent
+ EndOfTrack
+ IsSongPositionPointer
+ GetSongPositionPointerMidiBeat
+ SongPositionPointer
+ IsMidiStart
+ MidiStart
+ IsMidiContinue
+ MidiContinue
+ IsMidiStop
+ MidiStop
+ IsMidiClock
+ MidiClock
+ IsQuarterFrame
+ GetQuarterFrameSequencerNumber
+ GetQuarterFrameValue
+ QuarterFrame
+ IsFullFrame
+ GetFullFrameParameters
+ FullFrame
+ IsMidiMachineControlMessage
+ GetMidiMachineControlCommand
+ MidiMachineControlCommand
+ IsMidiMachineControlGoto
+ MidiMachineControlGoto
+ GetMidiNoteName
+ GetMidiNoteInHertz
+ IsMidiNoteBlack
+ GetGmInstrumentName
+ GetGmInstrumentBankName
+ GetRhythmInstrumentName
+ GetControllerName
{}
