[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-oboe-flowgraph-node]
path = "../aloe-oboe-flowgraph-node"
[package]
edition = "2021"
name = "aloe-oboe-flowgraph-source"
version = "0.1.0"