[dependencies.aloe-component]
path = "../aloe-component"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-graphics]
path = "../aloe-graphics"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-mouse]
path = "../aloe-mouse"
[package]
edition = "2021"
name = "aloe-stretchable"
version = "0.1.0"