[dependencies]
atomic = "*"
bitfield = "*"
lazy_static = "*"
libc = "*"
modular-bitfield = "*"
num = "*"
parking_lot = "*"
static_assertions = "*"
wchar = "*"
[dependencies.aloe-audio-interface]
path = "../aloe-audio-interface"
[dependencies.aloe-buttons]
path = "../aloe-buttons"
[dependencies.aloe-combobox]
path = "../aloe-combobox"
[dependencies.aloe-critical-section]
path = "../aloe-critical-section"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-math]
path = "../aloe-math"
[dependencies.aloe-network]
path = "../aloe-network"
[dependencies.aloe-slider]
path = "../aloe-slider"
[dependencies.aloe-undo]
path = "../aloe-undo"
[package]
edition = "2021"
name = "aloe-param"
version = "0.1.0"
