[dependencies]
libc = "*"
core-foundation-sys = "*"
[dependencies.aloe-char]
path = "../aloe-char"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-deps]
path = "../aloe-deps"
[package]
edition = "2021"
name = "aloe-string"
version = "0.1.0"
