[dependencies.aloe-char]
path = "../aloe-char"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-memory]
path = "../aloe-memory"
[dependencies.aloe-string]
path = "../aloe-string"
[package]
edition = "2021"
name = "aloe-math-expression"
version = "0.1.0"