[dependencies]
libc = "*"
parking_lot = "*"
[dependencies.aloe-codec]
path = "../aloe-codec"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-oboe-core]
path = "../aloe-oboe-core"
[dependencies.aloe-oboe-no-aaudio]
path = "../aloe-oboe-no-aaudio"
[package]
edition = "2021"
name = "aloe-oboe-stream"
version = "0.1.0"
