[dependencies]
atomic = "*"
bitfield = "*"
lazy_static = "*"
libc = "*"
modular-bitfield = "*"
num = "*"
parking_lot = "*"
static_assertions = "*"
wchar = "*"
[dependencies.aloe-array]
path = "../aloe-array"
[dependencies.aloe-atomic]
path = "../aloe-atomic"
[dependencies.aloe-critical-section]
path = "../aloe-critical-section"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-test]
path = "../aloe-test"
[dependencies.aloe-memory]
path = "../aloe-memory"
[dependencies.aloe-uuid]
path = "../aloe-uuid"
[dependencies.aloe-variant]
path = "../aloe-variant"
[package]
edition = "2021"
name = "aloe-container"
version = "0.1.0"
