[dependencies]
objc = "*"
objc-foundation = "0.1"
objc_id = "*"
[dependencies.icrate]
features = [ "AppKit", "AppKit_NSView", "Foundation", "Foundation_NSError", "Foundation_NSNotification" ]
version = "*"
[dependencies.aloe-core]
path = "../aloe-core"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-embedding]
path = "../aloe-embedding"
[dependencies.aloe-files]
path = "../aloe-files"
[dependencies.aloe-geometry]
path = "../aloe-geometry"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-time]
path = "../aloe-time"
[dependencies.aloe-url]
path = "../aloe-url"
[dependencies.aloe-video]
path = "../aloe-video"
[package]
edition = "2021"
name = "aloe-mac-video"
version = "0.1.0"
