[dependencies]
modular-bitfield = "*"
bitflags = "*"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-vst-persist]
path = "../aloe-vst-persist"
[dependencies.aloe-vst-types]
path = "../aloe-vst-types"
[package]
edition = "2021"
name = "aloe-vst-string"
version = "0.1.0"
