[dependencies]
atomic = "*"
bitfield = "*"
lazy_static = "*"
libc = "*"
modular-bitfield = "*"
num = "*"
parking_lot = "*"
static_assertions = "*"
wchar = "*"
[dependencies.aloe-audio-interface]
path = "../aloe-audio-interface"
[dependencies.aloe-component]
path = "../aloe-component"
[dependencies.aloe-critical-section]
path = "../aloe-critical-section"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-dsp]
path = "../aloe-dsp"
[dependencies.aloe-fft]
path = "../aloe-fft"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-math]
path = "../aloe-math"
[dependencies.aloe-memory]
path = "../aloe-memory"
[dependencies.aloe-parameter-type]
path = "../aloe-parameter-type"
[dependencies.aloe-sample-type]
path = "../aloe-sample-type"
[dependencies.aloe-smoothed-value]
path = "../aloe-smoothed-value"
[dependencies.aloe-threads]
path = "../aloe-threads"
[package]
edition = "2021"
name = "aloe-filter"
version = "0.1.0"
