[dependencies.aloe-component]
path = "../aloe-component"
[dependencies.aloe-container]
path = "../aloe-container"
[dependencies.aloe-derive]
path = "../aloe-derive"
[dependencies.aloe-events]
path = "../aloe-events"
[dependencies.aloe-geometry]
path = "../aloe-geometry"
[dependencies.aloe-graphics]
path = "../aloe-graphics"
[dependencies.aloe-deps]
path = "../aloe-deps"
[dependencies.aloe-keyboard]
path = "../aloe-keyboard"
[dependencies.aloe-label]
path = "../aloe-label"
[dependencies.aloe-menus]
path = "../aloe-menus"
[dependencies.aloe-mouse]
path = "../aloe-mouse"
[dependencies.aloe-network]
path = "../aloe-network"
[dependencies.aloe-valuetree]
path = "../aloe-valuetree"
[package]
edition = "2021"
name = "aloe-combobox"
version = "0.1.0"